#!/bin/bash

travis_retry go get github.com/tcnksm/ghr github.com/mitchellh/gox gopkg.in/alecthomas/gometalinter.v2

go test -v ./...
RESULT=$?

echo Done tests with exit code $RESULT
if [ "$RESULT" != "0" ]; then
  return $RESULT
fi

# Static analysis

gometalinter.v2 --install

echo ""
echo "gometalinter critical (should be no warnings):"
gometalinter.v1 --enable-all \
--concurrency=3 \
--deadline=10m \
./...
STATICRESULT1=$?

# Test cross-compilation. The binaries produced are also used for release
# upload in after_success if this is a release tag.

echo Cross-compiling releases...
mkdir -p "$GOPATH/releasing/idist" "$GOPATH/releasing/dist"

GOX_PARA=3

REPOS="github.com/$TRAVIS_REPO_SLUG/..."

# non-cgo crosscompile
gox -parallel=$GOX_PARA -osarch 'darwin/386 darwin/amd64 linux/386 linux/amd64 linux/arm linux/arm64 linux/ppc64 linux/ppc64le freebsd/386 freebsd/amd64 freebsd/arm openbsd/386 openbsd/amd64 netbsd/386 netbsd/amd64 netbsd/arm dragonfly/amd64 solaris/amd64 windows/386 windows/amd64' -output "$GOPATH/releasing/idist/ncdns-$TRAVIS_TAG-{{.OS}}_{{.Arch}}/bin/{{.Dir}}" $REPOS
RESULT2=$?

echo non-cgo crosscompile exited with code $RESULT2
echo critical gometalinter exited with code $STATICRESULT1

if [ "$RESULT2" != "0" ]; then
  return $RESULT2
fi
if [ "$STATICRESULT1" != "0" ]; then
  return $STATICRESULT1
fi
